# Generated by Django 6.0.6 on 2026-07-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('AEG', 'AEG'), ('GBBR', 'GBBR'), ('HPA', 'HPA'), ('Spring', 'Spring'), ('GBB', 'GBB')], max_length=20)),
                ('roles', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('pros', models.JSONField(default=list)),
                ('cons', models.JSONField(default=list)),
                ('best_for', models.JSONField(default=list)),
                ('not_for', models.JSONField(default=list)),
                ('extra_gear', models.JSONField(default=list)),
                ('budget_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
