from django.db import migrations


SCORES_BY_SLUG = {'1911-colt': {'beginner_friendly': 8,
               'comfort': 8,
               'cqb': 9,
               'drive': 7,
               'reliability': 8,
               'repair_cost': 7,
               'status': 7,
               'weight': 9},
 '1911-meu': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 7,
              'status': 7,
              'weight': 9},
 'aap-01-assassin': {'beginner_friendly': 9,
                     'comfort': 9,
                     'cqb': 10,
                     'drive': 9,
                     'reliability': 9,
                     'repair_cost': 8,
                     'status': 8,
                     'weight': 10},
 'aap-01c': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 7,
             'status': 7,
             'weight': 10},
 'ak-104-aeg': {'beginner_friendly': 8,
                'comfort': 7,
                'cqb': 7,
                'drive': 6,
                'reliability': 9,
                'repair_cost': 9,
                'status': 6,
                'weight': 7},
 'ak-105-aeg': {'beginner_friendly': 8,
                'comfort': 7,
                'cqb': 7,
                'drive': 6,
                'reliability': 9,
                'repair_cost': 9,
                'status': 6,
                'weight': 7},
 'ak-105-gbbr': {'beginner_friendly': 3,
                 'comfort': 7,
                 'cqb': 7,
                 'drive': 9,
                 'reliability': 7,
                 'repair_cost': 5,
                 'status': 9,
                 'weight': 5},
 'ak-12k-aeg': {'beginner_friendly': 8,
                'comfort': 7,
                'cqb': 7,
                'drive': 6,
                'reliability': 9,
                'repair_cost': 9,
                'status': 6,
                'weight': 7},
 'ak-47-aeg': {'beginner_friendly': 8,
               'comfort': 6,
               'cqb': 4,
               'drive': 6,
               'reliability': 9,
               'repair_cost': 9,
               'status': 6,
               'weight': 5},
 'ak-74m-aeg': {'beginner_friendly': 8,
                'comfort': 6,
                'cqb': 4,
                'drive': 6,
                'reliability': 9,
                'repair_cost': 9,
                'status': 6,
                'weight': 6},
 'ak-aeg': {'beginner_friendly': 9,
            'comfort': 6,
            'cqb': 4,
            'drive': 6,
            'reliability': 10,
            'repair_cost': 10,
            'status': 6,
            'weight': 6},
 'aks-74u-aeg': {'beginner_friendly': 8,
                 'comfort': 7,
                 'cqb': 7,
                 'drive': 6,
                 'reliability': 9,
                 'repair_cost': 9,
                 'status': 6,
                 'weight': 7},
 'aks-74u-gbbr': {'beginner_friendly': 3,
                  'comfort': 7,
                  'cqb': 7,
                  'drive': 9,
                  'reliability': 7,
                  'repair_cost': 5,
                  'status': 9,
                  'weight': 6},
 'arp556-aeg': {'beginner_friendly': 8,
                'comfort': 8,
                'cqb': 9,
                'drive': 7,
                'reliability': 8,
                'repair_cost': 8,
                'status': 7,
                'weight': 8},
 'arp9-aeg': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 8,
              'status': 7,
              'weight': 8},
 'bcm-mcmr-gbbr': {'beginner_friendly': 3,
                   'comfort': 7,
                   'cqb': 6,
                   'drive': 9,
                   'reliability': 7,
                   'repair_cost': 5,
                   'status': 9,
                   'weight': 6},
 'cm16-raider': {'beginner_friendly': 9,
                 'comfort': 8,
                 'cqb': 7,
                 'drive': 7,
                 'reliability': 9,
                 'repair_cost': 9,
                 'status': 7,
                 'weight': 8},
 'cm16-srxl': {'beginner_friendly': 9,
               'comfort': 8,
               'cqb': 7,
               'drive': 7,
               'reliability': 9,
               'repair_cost': 9,
               'status': 7,
               'weight': 7},
 'cz-p10c': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 7,
             'status': 7,
             'weight': 10},
 'cz-shadow-2': {'beginner_friendly': 6,
                 'comfort': 7,
                 'cqb': 8,
                 'drive': 8,
                 'reliability': 8,
                 'repair_cost': 6,
                 'status': 8,
                 'weight': 8},
 'daniel-defense-mk18-gbbr': {'beginner_friendly': 3,
                              'comfort': 7,
                              'cqb': 6,
                              'drive': 9,
                              'reliability': 7,
                              'repair_cost': 5,
                              'status': 9,
                              'weight': 6},
 'desert-eagle': {'beginner_friendly': 2,
                  'comfort': 4,
                  'cqb': 4,
                  'drive': 8,
                  'reliability': 6,
                  'repair_cost': 5,
                  'status': 10,
                  'weight': 7},
 'dragunov-svd': {'beginner_friendly': 3,
                  'comfort': 5,
                  'cqb': 1,
                  'drive': 8,
                  'reliability': 8,
                  'repair_cost': 6,
                  'status': 9,
                  'weight': 4},
 'f2000-aeg': {'beginner_friendly': 8,
               'comfort': 7,
               'cqb': 5,
               'drive': 7,
               'reliability': 8,
               'repair_cost': 8,
               'status': 7,
               'weight': 7},
 'fal-aeg': {'beginner_friendly': 3,
             'comfort': 5,
             'cqb': 1,
             'drive': 8,
             'reliability': 8,
             'repair_cost': 6,
             'status': 9,
             'weight': 4},
 'g36c-aeg': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 8,
              'status': 7,
              'weight': 8},
 'glock-18c': {'beginner_friendly': 8,
               'comfort': 9,
               'cqb': 10,
               'drive': 8,
               'reliability': 7,
               'repair_cost': 7,
               'status': 8,
               'weight': 10},
 'glock-34': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 7,
              'status': 7,
              'weight': 9},
 'glock-45': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 7,
              'status': 7,
              'weight': 10},
 'hk416-aeg': {'beginner_friendly': 8,
               'comfort': 7,
               'cqb': 5,
               'drive': 7,
               'reliability': 8,
               'repair_cost': 8,
               'status': 7,
               'weight': 6},
 'hk417-aeg': {'beginner_friendly': 3,
               'comfort': 5,
               'cqb': 1,
               'drive': 8,
               'reliability': 8,
               'repair_cost': 6,
               'status': 9,
               'weight': 4},
 'hk417-dmr': {'beginner_friendly': 3,
               'comfort': 5,
               'cqb': 1,
               'drive': 8,
               'reliability': 8,
               'repair_cost': 6,
               'status': 9,
               'weight': 4},
 'hk417-gbbr': {'beginner_friendly': 2,
                'comfort': 5,
                'cqb': 1,
                'drive': 9,
                'reliability': 7,
                'repair_cost': 5,
                'status': 10,
                'weight': 4},
 'hk45': {'beginner_friendly': 8,
          'comfort': 8,
          'cqb': 9,
          'drive': 7,
          'reliability': 8,
          'repair_cost': 7,
          'status': 7,
          'weight': 9},
 'jg-bar-10': {'beginner_friendly': 5,
               'comfort': 7,
               'cqb': 1,
               'drive': 6,
               'reliability': 8,
               'repair_cost': 9,
               'status': 6,
               'weight': 8},
 'jg-bar10': {'beginner_friendly': 5,
              'comfort': 7,
              'cqb': 1,
              'drive': 6,
              'reliability': 8,
              'repair_cost': 9,
              'status': 6,
              'weight': 8},
 'kac-sr16-gbbr': {'beginner_friendly': 3,
                   'comfort': 7,
                   'cqb': 6,
                   'drive': 9,
                   'reliability': 7,
                   'repair_cost': 5,
                   'status': 9,
                   'weight': 6},
 'kriss-vector': {'beginner_friendly': 8,
                  'comfort': 8,
                  'cqb': 9,
                  'drive': 7,
                  'reliability': 8,
                  'repair_cost': 8,
                  'status': 7,
                  'weight': 8},
 'l85a2-aeg': {'beginner_friendly': 8,
               'comfort': 7,
               'cqb': 5,
               'drive': 7,
               'reliability': 8,
               'repair_cost': 8,
               'status': 7,
               'weight': 5},
 'l96-aws': {'beginner_friendly': 4,
             'comfort': 6,
             'cqb': 1,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 8,
             'status': 8,
             'weight': 5},
 'm110-dmr': {'beginner_friendly': 3,
              'comfort': 5,
              'cqb': 1,
              'drive': 8,
              'reliability': 8,
              'repair_cost': 6,
              'status': 9,
              'weight': 4},
 'm110-gbbr': {'beginner_friendly': 2,
               'comfort': 4,
               'cqb': 1,
               'drive': 9,
               'reliability': 7,
               'repair_cost': 5,
               'status': 10,
               'weight': 4},
 'm14-ebr': {'beginner_friendly': 3,
             'comfort': 5,
             'cqb': 1,
             'drive': 8,
             'reliability': 8,
             'repair_cost': 6,
             'status': 9,
             'weight': 2},
 'm24': {'beginner_friendly': 4,
         'comfort': 6,
         'cqb': 1,
         'drive': 7,
         'reliability': 8,
         'repair_cost': 8,
         'status': 8,
         'weight': 5},
 'm24-sniper': {'beginner_friendly': 4,
                'comfort': 6,
                'cqb': 1,
                'drive': 7,
                'reliability': 8,
                'repair_cost': 8,
                'status': 8,
                'weight': 5},
 'm249-saw': {'beginner_friendly': 2,
              'comfort': 3,
              'cqb': 1,
              'drive': 8,
              'reliability': 8,
              'repair_cost': 6,
              'status': 9,
              'weight': 3},
 'm4-aeg': {'beginner_friendly': 10,
            'comfort': 8,
            'cqb': 7,
            'drive': 7,
            'reliability': 9,
            'repair_cost': 9,
            'status': 7,
            'weight': 7},
 'm40a3': {'beginner_friendly': 4,
           'comfort': 6,
           'cqb': 1,
           'drive': 7,
           'reliability': 8,
           'repair_cost': 8,
           'status': 8,
           'weight': 5},
 'm40a5': {'beginner_friendly': 4,
           'comfort': 6,
           'cqb': 1,
           'drive': 7,
           'reliability': 8,
           'repair_cost': 8,
           'status': 8,
           'weight': 5},
 'm60': {'beginner_friendly': 2,
         'comfort': 3,
         'cqb': 1,
         'drive': 8,
         'reliability': 8,
         'repair_cost': 6,
         'status': 9,
         'weight': 2},
 'mcx-virtus-aeg': {'beginner_friendly': 8,
                    'comfort': 7,
                    'cqb': 5,
                    'drive': 7,
                    'reliability': 8,
                    'repair_cost': 8,
                    'status': 7,
                    'weight': 6},
 'mg42': {'beginner_friendly': 2,
          'comfort': 3,
          'cqb': 1,
          'drive': 8,
          'reliability': 8,
          'repair_cost': 6,
          'status': 9,
          'weight': 1},
 'mk12-spr': {'beginner_friendly': 3,
              'comfort': 5,
              'cqb': 1,
              'drive': 8,
              'reliability': 8,
              'repair_cost': 6,
              'status': 9,
              'weight': 5},
 'mk18-aeg': {'beginner_friendly': 9,
              'comfort': 8,
              'cqb': 7,
              'drive': 7,
              'reliability': 9,
              'repair_cost': 9,
              'status': 7,
              'weight': 7},
 'mk18-gbbr': {'beginner_friendly': 3,
               'comfort': 7,
               'cqb': 6,
               'drive': 9,
               'reliability': 7,
               'repair_cost': 5,
               'status': 9,
               'weight': 6},
 'mk46': {'beginner_friendly': 2,
          'comfort': 3,
          'cqb': 1,
          'drive': 8,
          'reliability': 8,
          'repair_cost': 6,
          'status': 9,
          'weight': 4},
 'mk48': {'beginner_friendly': 2,
          'comfort': 3,
          'cqb': 1,
          'drive': 8,
          'reliability': 8,
          'repair_cost': 6,
          'status': 9,
          'weight': 2},
 'mp5-aeg': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 8,
             'status': 7,
             'weight': 8},
 'mp5a5': {'beginner_friendly': 8,
           'comfort': 8,
           'cqb': 9,
           'drive': 7,
           'reliability': 8,
           'repair_cost': 8,
           'status': 7,
           'weight': 8},
 'mp5k-aeg': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 8,
              'status': 7,
              'weight': 9},
 'mp5k-pdw': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 8,
              'status': 7,
              'weight': 8},
 'mp5sd6': {'beginner_friendly': 8,
            'comfort': 8,
            'cqb': 9,
            'drive': 7,
            'reliability': 8,
            'repair_cost': 8,
            'status': 7,
            'weight': 7},
 'mp7-aeg': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 8,
             'status': 7,
             'weight': 10},
 'mp7a1': {'beginner_friendly': 8,
           'comfort': 8,
           'cqb': 9,
           'drive': 7,
           'reliability': 8,
           'repair_cost': 8,
           'status': 7,
           'weight': 10},
 'mpx-aeg': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 8,
             'status': 7,
             'weight': 8},
 'mpx-pdw': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 8,
             'status': 7,
             'weight': 9},
 'mtw-billet': {'beginner_friendly': 2,
                'comfort': 8,
                'cqb': 7,
                'drive': 10,
                'reliability': 9,
                'repair_cost': 5,
                'status': 9,
                'weight': 8},
 'mtw-forged': {'beginner_friendly': 2,
                'comfort': 8,
                'cqb': 7,
                'drive': 10,
                'reliability': 9,
                'repair_cost': 5,
                'status': 9,
                'weight': 7},
 'mtw-tactical': {'beginner_friendly': 2,
                  'comfort': 8,
                  'cqb': 7,
                  'drive': 10,
                  'reliability': 9,
                  'repair_cost': 5,
                  'status': 9,
                  'weight': 8},
 'mws-m4-gbbr': {'beginner_friendly': 5,
                 'comfort': 7,
                 'cqb': 5,
                 'drive': 9,
                 'reliability': 9,
                 'repair_cost': 6,
                 'status': 9,
                 'weight': 6},
 'novritsch-ssp1': {'beginner_friendly': 8,
                    'comfort': 8,
                    'cqb': 9,
                    'drive': 7,
                    'reliability': 8,
                    'repair_cost': 7,
                    'status': 7,
                    'weight': 9},
 'novritsch-ssp2': {'beginner_friendly': 8,
                    'comfort': 8,
                    'cqb': 9,
                    'drive': 7,
                    'reliability': 8,
                    'repair_cost': 7,
                    'status': 7,
                    'weight': 9},
 'novritsch-ssp5': {'beginner_friendly': 6,
                    'comfort': 8,
                    'cqb': 9,
                    'drive': 8,
                    'reliability': 8,
                    'repair_cost': 6,
                    'status': 9,
                    'weight': 8},
 'p90-tr': {'beginner_friendly': 8,
            'comfort': 8,
            'cqb': 9,
            'drive': 7,
            'reliability': 8,
            'repair_cost': 8,
            'status': 7,
            'weight': 8},
 'pkp-pecheneg': {'beginner_friendly': 2,
                  'comfort': 3,
                  'cqb': 1,
                  'drive': 8,
                  'reliability': 8,
                  'repair_cost': 6,
                  'status': 9,
                  'weight': 1},
 'polarstar-f2-ak': {'beginner_friendly': 2,
                     'comfort': 8,
                     'cqb': 7,
                     'drive': 10,
                     'reliability': 9,
                     'repair_cost': 5,
                     'status': 9,
                     'weight': 6},
 'polarstar-f2-m4': {'beginner_friendly': 2,
                     'comfort': 8,
                     'cqb': 7,
                     'drive': 10,
                     'reliability': 9,
                     'repair_cost': 5,
                     'status': 9,
                     'weight': 7},
 'polarstar-kythera-ak': {'beginner_friendly': 2,
                          'comfort': 8,
                          'cqb': 7,
                          'drive': 10,
                          'reliability': 9,
                          'repair_cost': 5,
                          'status': 9,
                          'weight': 6},
 'polarstar-kythera-m4': {'beginner_friendly': 2,
                          'comfort': 8,
                          'cqb': 7,
                          'drive': 10,
                          'reliability': 9,
                          'repair_cost': 5,
                          'status': 9,
                          'weight': 7},
 'rpd': {'beginner_friendly': 2,
         'comfort': 3,
         'cqb': 1,
         'drive': 8,
         'reliability': 8,
         'repair_cost': 6,
         'status': 9,
         'weight': 3},
 'rpk-16': {'beginner_friendly': 2,
            'comfort': 3,
            'cqb': 1,
            'drive': 8,
            'reliability': 8,
            'repair_cost': 6,
            'status': 9,
            'weight': 4},
 'rpk-74': {'beginner_friendly': 2,
            'comfort': 3,
            'cqb': 1,
            'drive': 8,
            'reliability': 8,
            'repair_cost': 6,
            'status': 9,
            'weight': 4},
 'scar-l-aeg': {'beginner_friendly': 8,
                'comfort': 7,
                'cqb': 5,
                'drive': 7,
                'reliability': 8,
                'repair_cost': 8,
                'status': 7,
                'weight': 6},
 'scorpion-evo-3': {'beginner_friendly': 8,
                    'comfort': 8,
                    'cqb': 9,
                    'drive': 7,
                    'reliability': 8,
                    'repair_cost': 8,
                    'status': 7,
                    'weight': 9},
 'sig-m18': {'beginner_friendly': 8,
             'comfort': 8,
             'cqb': 9,
             'drive': 7,
             'reliability': 8,
             'repair_cost': 7,
             'status': 7,
             'weight': 9},
 'sig-mcx-gbbr': {'beginner_friendly': 3,
                  'comfort': 7,
                  'cqb': 6,
                  'drive': 9,
                  'reliability': 7,
                  'repair_cost': 5,
                  'status': 9,
                  'weight': 6},
 'sig-p226': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 7,
              'status': 7,
              'weight': 9},
 'sig-p320': {'beginner_friendly': 8,
              'comfort': 8,
              'cqb': 9,
              'drive': 7,
              'reliability': 8,
              'repair_cost': 7,
              'status': 7,
              'weight': 9},
 'silverback-srs': {'beginner_friendly': 3,
                    'comfort': 7,
                    'cqb': 1,
                    'drive': 8,
                    'reliability': 9,
                    'repair_cost': 7,
                    'status': 9,
                    'weight': 6},
 'silverback-tac41': {'beginner_friendly': 3,
                      'comfort': 7,
                      'cqb': 1,
                      'drive': 8,
                      'reliability': 9,
                      'repair_cost': 7,
                      'status': 9,
                      'weight': 6},
 'sr-25-gbbr': {'beginner_friendly': 2,
                'comfort': 5,
                'cqb': 1,
                'drive': 9,
                'reliability': 7,
                'repair_cost': 5,
                'status': 10,
                'weight': 4},
 'sr25-dmr': {'beginner_friendly': 3,
              'comfort': 5,
              'cqb': 1,
              'drive': 8,
              'reliability': 8,
              'repair_cost': 6,
              'status': 9,
              'weight': 4},
 'sr25-gbbr': {'beginner_friendly': 2,
               'comfort': 5,
               'cqb': 1,
               'drive': 9,
               'reliability': 7,
               'repair_cost': 5,
               'status': 10,
               'weight': 4},
 'ssg96': {'beginner_friendly': 4,
           'comfort': 6,
           'cqb': 1,
           'drive': 7,
           'reliability': 8,
           'repair_cost': 8,
           'status': 8,
           'weight': 5},
 'stoner-96': {'beginner_friendly': 2,
               'comfort': 3,
               'cqb': 1,
               'drive': 8,
               'reliability': 8,
               'repair_cost': 6,
               'status': 9,
               'weight': 4},
 'svd-aeg': {'beginner_friendly': 3,
             'comfort': 5,
             'cqb': 1,
             'drive': 8,
             'reliability': 8,
             'repair_cost': 6,
             'status': 9,
             'weight': 4},
 'tavor-tar-21-aeg': {'beginner_friendly': 8,
                      'comfort': 7,
                      'cqb': 5,
                      'drive': 7,
                      'reliability': 8,
                      'repair_cost': 8,
                      'status': 7,
                      'weight': 6},
 'thompson-aeg': {'beginner_friendly': 8,
                  'comfort': 7,
                  'cqb': 5,
                  'drive': 7,
                  'reliability': 8,
                  'repair_cost': 8,
                  'status': 7,
                  'weight': 5},
 'tm-vsr10': {'beginner_friendly': 5,
              'comfort': 7,
              'cqb': 1,
              'drive': 7,
              'reliability': 9,
              'repair_cost': 9,
              'status': 8,
              'weight': 8},
 'tokyo-marui-vsr-10': {'beginner_friendly': 5,
                        'comfort': 7,
                        'cqb': 1,
                        'drive': 7,
                        'reliability': 9,
                        'repair_cost': 9,
                        'status': 8,
                        'weight': 8},
 'ump45': {'beginner_friendly': 8,
           'comfort': 8,
           'cqb': 9,
           'drive': 7,
           'reliability': 8,
           'repair_cost': 8,
           'status': 7,
           'weight': 8},
 'ump9': {'beginner_friendly': 8,
          'comfort': 8,
          'cqb': 9,
          'drive': 7,
          'reliability': 8,
          'repair_cost': 8,
          'status': 7,
          'weight': 8},
 'usp-compact': {'beginner_friendly': 8,
                 'comfort': 8,
                 'cqb': 9,
                 'drive': 7,
                 'reliability': 8,
                 'repair_cost': 7,
                 'status': 7,
                 'weight': 10},
 'vector-aeg': {'beginner_friendly': 8,
                'comfort': 8,
                'cqb': 9,
                'drive': 7,
                'reliability': 8,
                'repair_cost': 8,
                'status': 7,
                'weight': 8},
 'vp9': {'beginner_friendly': 8,
         'comfort': 8,
         'cqb': 9,
         'drive': 7,
         'reliability': 8,
         'repair_cost': 7,
         'status': 7,
         'weight': 10},
 'vss-vintorez': {'beginner_friendly': 3,
                  'comfort': 5,
                  'cqb': 1,
                  'drive': 8,
                  'reliability': 8,
                  'repair_cost': 6,
                  'status': 9,
                  'weight': 6},
 'walther-ppq': {'beginner_friendly': 8,
                 'comfort': 8,
                 'cqb': 9,
                 'drive': 7,
                 'reliability': 8,
                 'repair_cost': 7,
                 'status': 7,
                 'weight': 10},
 'well-mb01': {'beginner_friendly': 6,
               'comfort': 5,
               'cqb': 1,
               'drive': 5,
               'reliability': 7,
               'repair_cost': 10,
               'status': 5,
               'weight': 5},
 'wolverine-inferno-gen2': {'beginner_friendly': 2,
                            'comfort': 8,
                            'cqb': 7,
                            'drive': 10,
                            'reliability': 9,
                            'repair_cost': 5,
                            'status': 9,
                            'weight': 7},
 'wolverine-reaper-ak': {'beginner_friendly': 2,
                         'comfort': 8,
                         'cqb': 7,
                         'drive': 10,
                         'reliability': 9,
                         'repair_cost': 5,
                         'status': 9,
                         'weight': 6},
 'wolverine-reaper-m4': {'beginner_friendly': 2,
                         'comfort': 8,
                         'cqb': 7,
                         'drive': 10,
                         'reliability': 9,
                         'repair_cost': 5,
                         'status': 9,
                         'weight': 7}}


def calibrate_product_scores(apps, schema_editor):
    Product = apps.get_model("picker", "Product")

    for product in Product.objects.all():
        scores = SCORES_BY_SLUG.get(product.slug)
        if scores is None:
            continue

        product.scores = scores
        product.save(update_fields=["scores"])


def reverse_calibration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0004_refine_weight_scores"),
    ]

    operations = [
        migrations.RunPython(
            calibrate_product_scores,
            reverse_calibration,
        ),
    ]
